language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
    - vendor
install:
  - composer install
script:
  - composer test
notifications:
  email:
    recipients:
      - stronati.a+fantasyfootballquotationsparser@gmail.com
    on_success: change
    on_failure: always
